/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonGamefinder {
        "disabled": boolean;
        "icon": string;
        "size": string;
        "variant": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TextfieldGamefinder {
        "color": string;
        "disabled": boolean;
        "helptext": string;
        "icon": string;
        "label": string;
        "placeholder": string;
        "state": string;
        "value": string;
    }
}
export interface ButtonGamefinderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonGamefinderElement;
}
export interface TextfieldGamefinderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTextfieldGamefinderElement;
}
declare global {
    interface HTMLButtonGamefinderElement extends Components.ButtonGamefinder, HTMLStencilElement {
    }
    var HTMLButtonGamefinderElement: {
        prototype: HTMLButtonGamefinderElement;
        new (): HTMLButtonGamefinderElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTextfieldGamefinderElement extends Components.TextfieldGamefinder, HTMLStencilElement {
    }
    var HTMLTextfieldGamefinderElement: {
        prototype: HTMLTextfieldGamefinderElement;
        new (): HTMLTextfieldGamefinderElement;
    };
    interface HTMLElementTagNameMap {
        "button-gamefinder": HTMLButtonGamefinderElement;
        "my-component": HTMLMyComponentElement;
        "textfield-gamefinder": HTMLTextfieldGamefinderElement;
    }
}
declare namespace LocalJSX {
    interface ButtonGamefinder {
        "disabled"?: boolean;
        "icon"?: string;
        "onGfClick"?: (event: ButtonGamefinderCustomEvent<boolean>) => void;
        "size"?: string;
        "variant"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TextfieldGamefinder {
        "color"?: string;
        "disabled"?: boolean;
        "helptext"?: string;
        "icon"?: string;
        "label"?: string;
        "onValueChange"?: (event: TextfieldGamefinderCustomEvent<any>) => void;
        "placeholder"?: string;
        "state"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "button-gamefinder": ButtonGamefinder;
        "my-component": MyComponent;
        "textfield-gamefinder": TextfieldGamefinder;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-gamefinder": LocalJSX.ButtonGamefinder & JSXBase.HTMLAttributes<HTMLButtonGamefinderElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "textfield-gamefinder": LocalJSX.TextfieldGamefinder & JSXBase.HTMLAttributes<HTMLTextfieldGamefinderElement>;
        }
    }
}
